### ISSUE TITLE
Adaptive sequencing watchfolder question

### ISSUE THREAD

**Issue by ggrimes** [LooseLab/ROBIN#56]
For the `watchfolder` input, does the output of the adaptive sequencing aligned file need to come from [readfish](https://looselab.github.io/readfish/toml.html) pipeline or can you also use the MinKNOW [adaptive-sampling] (https://nanoporetech.com/document/adaptive-sampling) pipeline.

If you can use the MinKNOW [adaptive-sampling]  pipeline, what bed file would you use and input for the target regions for the rCNS2 analysis?

https://github.com/LooseLab/ROBIN/blob/main/src/robin/resources/rCNS2_panel_name_uniq.bed

Thanks

Graeme

**Comment by mattloose** [comment]
Thanks for your question.

The panel we would use is:

src/robin/resources/panel_11092024_5kb_pad.bed

We have used this with built in adaptive sampling on MinKNOW and it works very well - in fact this is our preferred approach for others who use this pipeline.

The watch folder will be the output folder containing bam files from MinKNOW which are aligned to an hg38 reference with high accuracy base calling and methylation calling switched on.

It is not a folder generated by readfish.

I hope this helps.
