### ISSUE TITLE
Missing NanoDX and PanNanoDX classifications in PDF report

### ISSUE THREAD

**Issue by mwhamgenomics** [LooseLab/ROBIN#70]
When I run 'Generate Report' on the live page to generate a PDF, the 'NanoDX' and 'PanNanoDX' entries that are [expected](https://github.com/LooseLab/ROBIN_test_set_A/blob/main/resources/NA12878_05_NB4_06_22Rv1_07_run_report.pdf) to appear at the top of the page are missing - see screenshot.

<img width="827" alt="Screenshot 2024-11-13 at 17 13 23" src="https://github.com/user-attachments/assets/da02b70e-3c57-45f7-8460-fdf4969d5b11">

This happens because the CSV files created in the output folder are called NanoDX_scores.csv and PanNanoDX_scores.csv, but the [PDF generation process](https://github.com/LooseLab/ROBIN/blob/33d084b027921f85506a5058182346e3027eed8a/src/robin/reporting/report.py#L140) looks for files named nanoDX_scores.csv and pannanodx_scores.csv. If I try updating these names to match what's generated, the two missing classifications now appear again.

**Comment by mattloose** [comment]
Would you be able to check out the branch issues/issue70 and see if this resolves the pdf generation process for you? I've made this fix backwards compatible. If it resolves it I will merge into the main branch.

**Comment by mwhamgenomics** [comment]
Thanks, I can confirm that this fixes it! I'm also getting the 'classifications over time' plots now, which I wasn't before. This is now resolved.

**Comment by mattloose** [comment]
Brilliant. Thank you for confirming. I will merge this into the main branch.
