### ISSUE TITLE
ROBIN not reading files transfered to watchfolder via rsync 

### ISSUE THREAD

**Issue by hbrooks0639** [LooseLab/ROBIN#77]
We have been using ROBIN on a windows PC with WSL installed and have set up file transfer with rysnc which is moving the files from the c drive to the ROBIN watch folder but they are not being seen by ROBIN. If I move one of the files myself by copy and pasting into the watch folder, ROBIN finds the file immediately.

**Comment by mattloose** [comment]
Thanks - this is a known issue and something that we intend to address asap. Will post here when it is resolved.

**Comment by mattloose** [comment]
Hi @hbrooks0639,

I have created a version of robin that should address this issue - its on the [dev](https://github.com/LooseLab/ROBIN/tree/dev) branch. If you could test this and confirm it works for you I will merge this feature into the main branch.

**Comment by hbrooks0639** [comment]
Hi @mattloose 

We have tested this and it works. Files are being moved and analysed successfully.

**Comment by mattloose** [comment]
Great - thank you - merged into main.

**Comment by samuelmontgomery** [comment]
Hi @hbrooks0639 - are you able to share some insight on how you've configured it to run with WSL2?
Are you running ReadFish on WSL2 as well? I am looking at setting this up on a Windows workstation we currently use for Nanopore sequencing with a P2 Solo, but was under the impression dorado on windows doesn't play nice with WSL2-installed ubuntu

**Comment by hbrooks0639** [comment]
Hi @samuelmontgomery,  We worked around this issue by letting Minknow create the BAM files in Windows like we would normally do on any Nanopore run and then used a cron job to Rsync copy the bam files over to WSL linux folder every 10 minutes.
